#!/bin/bash
#Created from mksh on 2013年 08月 03日 星期六 20:53:09 CST
#Description: 

pkgs=(build-essential apache2 passenger_apache2 openssl mysql database)
for pkg in ${pkgs[*]};do
  knife cookbook github install opscode-cookbook/$pkg
done
echo finished!
